apiVersion: v1
kind: Service
metadata:
  name: ollama
  labels:
    app: ollama
spec:
  selector:
    app: ollama
  ports:
    - protocol: TCP
      port: 11434          # The port to expose internally
      targetPort: 11434     # The container port the traffic is directed to
  type: ClusterIP           # Internal service, not exposed externally
